
{
  "before_script": [
    "sudo apt-get update",
    "sudo apt-get install build-essential software-properties-common -y",
    "sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev libc6-dev zlib1g-dev g++ -y",
    "uname -a",
    "cat /etc/issue",
    "wget http://www.mpfr.org/mpfr-current/mpfr-3.1.5.tar.gz",
    "mkdir /home/travis/build/zhaibin18/mpfr",
    "tar -zxf mpfr-3.1.5.tar.gz",
    "cd mpfr-3.1.5",
    "./configure --prefix=/home/travis/build/zhaibin18/mpfr && make && make install",
    "cd ~",
    "wget https://ftp.gnu.org/gnu/gmp/gmp-6.1.1.tar.xz",
    "tar -pxf gmp-6.1.1.tar.xz",
    "mkdir /home/travis/build/zhaibin18/gmp",
    "cd gmp-6.1.1",
    "./configure --prefix=/home/travis/build/zhaibin18/gmp && make && make install",
    "cd ~",
    "wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz",
    "mkdir mpc",
    "tar -zxf mpc-1.0.3.tar.gz",
    "cd mpc-1.0.3",
    "./configure --prefix=/home/travis/build/zhaibin18/mpc --with-gmp=/home/travis/build/zhaibin18/gmp --with-mpfr=/home/travis/build/zhaibin18/mpfr && make && make install",
  ],
  "language": "ruby",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
