
{
  "before_script": [
    "sudo apt-get update",
    "sudo apt-get install build-essential software-properties-common -y",
    "sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev libc6-dev zlib1g-dev g++ -y",
    "uname -a",
    "cat /etc/issue",
    "wget http://www.netgull.com/gcc/releases/gcc-6.2.0/gcc-6.2.0.tar.gz",
    "tar -zxvfgcc-6.2.0.tar.gz "
  ],
  "language": "ruby",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
