
{
  "before_script": [
    "sudo apt-get update",
    "sudo apt-get -y install gcc-5.0",
    "uname",
    "cat /etc/issue"
  ],
  "language": "ruby",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
